version: "3"
services:
  mysqlsrv:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=quizdb
      - MYSQL_USER=quizusr
      - MYSQL_PASSWORD=quizpasswd
      - MYSQL_ROOT_PASSWORD=rootpasswd
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  migrations:
    build: .
    command: "--migrate"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=tcp(mysqlsrv)
      - DB_DATABASE=quizdb
      - DB_USERNAME=quizusr
      - DB_PASSWORD=quizpasswd
    volumes:
      - ./:/app
    depends_on:
      - mysqlsrv
